### PR TITLE
Improve search box performance

### PR DESCRIPTION
**Pull request by jonahsnider**
This fixes a performance issue where focusing the search box or typing a character would block the entire page, causing the entire UI to freeze up for up to several seconds.

This issue has been bothering me for months at this point, and it ends up being a very simple fix for the frontend: just update a single dependency!

The actual issue is from the `react-select` dependency and was [reported here](https://github.com/JedWatson/react-select/issues/3128) and [fixed here](https://github.com/JedWatson/react-select/pull/4034).

I discovered this was the cause of the issue by recording a performance profile from the Chrome DevTools, seeing that the culprit was in a file named `react-select-cac0a5ae.browser.esm.js`, then searching around the `react-select` GitHub repository to find others experiencing the same issue.

### CODE REVIEW

**Comment by jonahsnider** [comment]
I think I spoke too soon, it looks like the search box performance is still quite subpar. I looked at a performance profile I recorded with this PR's changes applied and it looks like the bottleneck is now somewhere else. Baby steps I guess?

**Comment by avgupta456** [comment]
Hey, thank you so much for raising this issue and proposing a solution! I will take a couple weeks off now that the competition season is over, but I will definitely come back to this and hopefully find a solution. I agree the current performance is very suboptimal.

**Comment by jonahsnider** [comment]
Thanks for the update! Definitely no rush on working on this — now that comp season is over there's not much scouting that needs to be going on anyway.

**Comment by avgupta456** [comment]
I ended up redoing the entire site. Let me know if you're still running into issues :)

**Pull request closed without merging**
